---
galaxy_info:
  role_name: kubernetes
  author: luvis-sirpi
  description: Install kubeadm, kubelet, kubectl
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble]
    - name: EL
      versions: ["9"]
dependencies:
  - role: containerd
