---
- name: Check if node is already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf
  tags: [worker]

- name: Join cluster
  command: "{{ hostvars[groups['masters'][0]].kubeadm_join_command }}"
  when: not kubelet_conf.stat.exists
  changed_when: true
  tags: [worker]

- name: Ensure kubelet is running
  service:
    name: kubelet
    state: started
    enabled: true
  tags: [worker]
