# Auto-generated by Terraform — do not edit manually.
# Re-run `terraform apply` to regenerate after instance changes.

[masters]
${master_name} ansible_host=${master_public_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_private_key_path}

[workers]
%{ for w in workers ~}
${w.name} ansible_host=${w.public_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_private_key_path}
%{ endfor ~}

[k8s_cluster:children]
masters
workers

[k8s_cluster:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
cloud_provider=aws
disable_host_firewall=true
